/** @format */

import {Dimensions, StyleSheet} from 'react-native';
import {Colors, Fonts, Metrics} from '../../theme';

export default StyleSheet.create({
  container: {
    backgroundColor: Colors.screenBackground,
    flex: 1,
  },
  swipeListView: {
    backgroundColor: 'red',
    paddingHorizontal: 5,
  },
  frontRowView: {
    // height: 70,
    // marginVertical: 5,
    marginHorizontal: 20,
    borderRadius: 8,
    // flexDirection: 'row',
    justifyContent: 'space-between',
    // paddingHorizontal: 8,
    padding: 8,
    marginBottom: 16,
    //SHADOW
    shadowColor: Colors.teal,
    shadowOpacity: 0.5,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
    elevation: 6,
  },
  nameLocationView: {
    // backgroundColor: 'red',
  },
  icon: {
    resizeMode: 'contain',
    alignSelf: 'flex-end',
    width: 30,
    height: 30,
  },
  radiusView: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  frontRowtxt: {
    fontSize: 14,
    // paddingTop: 10,
  },
  frontRowDestxt: {
    // textAlign: 'center',
    fontSize: 12,
    // paddingVertical: 12,
  },
  backRowView: {
    // backgroundColor: 'black',
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginVertical: 5,
    marginHorizontal: 20,
    height: 50,
  },
  backRowEditView: {
    backgroundColor: 'blue',
    flex: 1,
    justifyContent: 'center',
    // height: 82,
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    paddingLeft: 20,
    // elevation: 6,

    // marginHorizontal: 20,
    // borderRadius: 8,
    // // flexDirection: 'row',
    // justifyContent: 'space-between',
    // // paddingHorizontal: 8,
    // padding: 8,
    // //SHADOW
    // shadowColor: Colors.teal,
    // shadowOpacity: 0.5,
    // shadowOffset: {width: 0, height: 2},
    // shadowRadius: 8,
    // elevation: 6,
  },
  backRowDeleteView: {
    backgroundColor: 'red',
    flex: 1,
    justifyContent: 'center',
    borderBottomRightRadius: 10,
    borderTopRightRadius: 10,
    // height: 82,
    paddingRight: 20,
    elevation: 6,
    shadowColor: Colors.teal,
  },
  backRowEditTxt: {
    color: Colors.white,
    fontSize: 16,
  },
  backRowDeleteTxt: {
    color: Colors.white,
    fontSize: 16,
    textAlign: 'right',
  },
  addIconViewStyles: {
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.powderBlue,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 6,
    borderRadius: 60,
    backgroundColor: Colors.powderBlue,
    position: 'absolute',
    bottom: 25,
    // right: 15,
    alignSelf: 'center',
  },
  addIconStyles: {
    resizeMode: 'contain',
    tintColor: Colors.teal,
    width: 65,
    height: 65,
  },
  emptytxtView: {
    // flex: 1,
    // backgroundColor: Colors.teal,
    // justifyContent: 'center',
    alignItems: 'center',
    // marginTop: 200,
  },
  reminderIcon: {
    resizeMode: 'contain',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').width,
    opacity: 0.3,
    tintColor: Colors.teal,
  },
  emptyTxt: {
    fontSize: 24,
    color: Colors.teal,
    // marginVertical: 10,
    opacity: 0.5,
  },
  shadowStyle: {
    width: 200,
    height: 200,
    borderRadius: 100,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
});
